name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.1, 7.2, 7.3, 7.4, 8.0]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies + PHPUnit 7
        if: ${{ matrix.php == '7.1' }}
        run: |
          composer update --with='phpunit/phpunit:^7.5' --${{ matrix.dependency-version }} --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Install dependencies + PHPUnit 8
        if: ${{ matrix.php == '7.2' }}
        run: |
          composer update --with='phpunit/phpunit:^8.0' --${{ matrix.dependency-version }} --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Install dependencies + PHPUnit 9
        if: ${{ matrix.php != '7.1' && matrix.php != '7.2' }}
        run: |
          composer update --with='phpunit/phpunit:^9.0' --${{ matrix.dependency-version }} --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Execute tests
        run: vendor/bin/phpunit
